# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K4x9V9TrgpZ4Va80UoeDgAPsgKLoS90g

비밀번호 발송 메일 프로그램
"""

print('회원 정보를 입력하세요.')
userName = input('이름: ')
userMail = input('메일: ')
userId = input('아이디: ')
userPw = input('비밀번호: ')

print('To. '+userMail+'\n'
+'▶ 아이디 및 비밀번호 확인'+'\n'
+userName+' 고객님 안녕하세요.'+'\n'
+'고객님의 아이디와 비밀번호는 아래와 같습니다.'+'\n'
+'아이디 : '+userId+'\n'+'비밀번호 : '+userPw)

"""원의 면적과 둘레 구하기"""

radius = int(input('원의 반지름을 입력하시오: '))
area = 3.14*radius**2
circum = 3.14*radius*2
print('반지름 %.2f의 면적은 = %.2f' %(radius,area)+'\n'
      +'반지름 %.2f의 둘레는 = %.2f' %(radius,circum))

print('반지름 %d의 면적은 = %.2f' %(radius,area)+'\n'
      +'반지름 %d의 둘레는 = %.2f' %(radius,circum))

"""차량 2부제 프로그램"""

carNum = int(input('차량 번호: '))
if carNum % 2 == 0:
  print('짝수일에 입차 가능합니다.')
else:
  print('홀수일에 입차 가능합니다.')

from datetime import datetime
dayNum = datetime.today().day
carNum = int(input('차량 번호: '))
print('오늘 날짜 : %d일' %dayNum)
if dayNum % 2 == 0:
  print('오늘 입차: 번호가 짝수인 차량')
else:
  print('오늘 입차: 번호가 홀수인 차량')
if dayNum % 2 == carNum %2:
  print('귀하의 차량은 입차 가능합니다.')
else:
  print('귀하의 차량은 입차 불가합니다.')

amount = float(input('전기 사용량: '))

if amount > 400:
  unitPrice = 280.6
  basicPrice = 7300
elif amount > 200: #201~400
  unitPrice = 187.9
  basicPrice = 1600
else:
  unitPrice = 99.3
  basicPrice = 910

totalPrice = amount*unitPrice + basicPrice
print('사용량: %.1f kwh' %amount)
print('기본요금: %.1f 원' %basicPrice)
print('단가: %.1f 원' %unitPrice)
print('전기요금: %.1f원' %totalPrice)

"""로또 번호"""

import random
lotto = []
for i in range(6):
  num = random.randint(1,45)
  if num not in lotto:
    lotto.append(num)
print(lotto)

while len(lotto) < 6:
  num = random.randint(1,45)
  if num not in lotto:
    lotto.append(num)
print(lotto)

import random
random.randint(1,45)

from random import *
randint(1,45)

"""출석부 관리 시스템"""

students = ["정우람", "박으뜸", "배힘찬", "천영웅", "신석기", "배민규", "전민수", "박건우", "박찬호", "이승엽"]
print(students)

students.sort()
print(students)

sorted(students)

students.remove('박찬호')
print(students)

students[:3]

students.append('이병규')
print(students)

students.reverse()
print(students)

ind = students.index('정우람')

students[ind] = '정잘남'
print(students)

"""튜플"""

members = {}

for i in range(2):
  id = input('아이디 입력: ')
  pw = input('비밀번호 입력: ')
  members[id] = pw

for key in members:
  print(key)
  print(members[key])

"""계산기 프로그램"""

def add():  # 덧셈
    print('덧셈 결과 : ', inputNumber1 + inputNumber2)

def sub():  # 뺄셈
    print('뺄셈 결과 : ', inputNumber1 - inputNumber2)

def mul():  # 곱셈
    print('곱셈 결과 : ', inputNumber1 * inputNumber2)

def div():  # 나눗셈
    print('나눗셈 결과 : ', inputNumber1 / inputNumber2)

def calculator(): # 계산기
    if(selectOperator == 1):
        add()
    elif(selectOperator == 2):
        sub()
    elif(selectOperator == 3):
        mul()
    elif(selectOperator == 4):
        div()

inputNumber1 = float(input('숫자를 입력하세요. '))
selectOperator = int(input('연산자를 선택하세요. 1.덧셈, 2.뺄셈, 3.곱셈, 4.나눗셈 '))
inputNumber2 = float(input('숫자를 입력하세요. '))

calculator()

standardPrice = {'쌀':9900, '상추':1900,'고추':2900,'마늘':8900,'통닭':5600,'햄':6900, '치즈':3900}

def getDiscountPrice(rate):
    dcPrice = {}
    for goods in standardPrice.keys():
        disPri = int(standardPrice[goods] * (1 - (rate / 100)))
        dcPrice[goods] = disPri
    return dcPrice

def printPrice(priceList):
    for goods in priceList.keys():
        print(goods, '\t:', standardPrice[goods], '원\t', inputData, '%DC ->', priceList[goods], '원')

print('---------------------------------------------')
print('-- 할인마트 오늘의 할인 가격표 출력 시스템 --')
print('---------------------------------------------')

inputData = int(input('오늘의 할인율을 입력하세요. '))
discountPrice = getDiscountPrice(inputData)

printPrice(discountPrice)
print('---------------------------------------------')